server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springData?serverTimezone=GMT%2b8
    username: root
    password: hswhy172

mybatis:
  mapper-locations: classpath:mapper/*.xml